name       : nautilus-folder-icons
version    : 3.0
release    : 5
source     :
    - https://github.com/bilelmoussaoui/nautilus-folder-icons/archive/3.0.tar.gz : 25fa6f164f50ed84ee6fa6d7a6004cb5190051847a5c3895f41bf1b426ad2565
homepage   : https://github.com/bilelmoussaoui/nautilus-folder-icons
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Change your nautilus directories icons easily
description: |
    An extension for Nautilus that makes changing folders icons easy.
builddeps  :
    - pkgconfig(appstream-glib)
    - vala
rundeps    :
    - nautilus-python
setup      : |
    find . -type f -exec sed -i 's|#!/usr/bin/python2|#!/usr/bin/python3|g' {} \;
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
